### ISSUE TITLE
✨ Feat: Add a footer

### ISSUE THREAD

**Issue by murtazajoo** [murtazajoo/openSourcer#8]
### What feature?

The website is lacking the footer :(

- add a footer 
- in the footer add  only this 
> open source is awesome 💜
OpenSourcer is an open-source project. Feel free to contribute and help us to make this project better
Copyright © 2023 by openSourcer. Under [MIT License](https://github.com/murtazajoo/openSourcer/blob/main/LICENSE)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this feature

**Comment by murtazajoo** [comment]
Hello @murtazajoo! Congratulations on creating your first issue! 🎉 We appreciate your contribution and want to assure you that we're on it. We'll do our best to resolve the issue promptly. If you have any additional information or details to share about the issue, please let us know. We're here to help! Thanks again for taking the time to report this issue. We value your feedback and look forward to working together to address it. Best regards, Your Project Team<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/murtazajooercontributing.md)</p>

**Comment by akj2018** [comment]
Hi, I would like to take this issue. Please assign it to me. 
Thank you!

**Comment by murtazajoo** [comment]
Great its All Yours

**Comment by yhimanshu22** [comment]
Hi murtazajoo,
I'm interested in taking the first issue. I'm new to this project, but I'm eager to learn and contribute. I've read the issue description and I think I have a good understanding of what needs to be done.
please assign it to me.

**Comment by murtazajoo** [comment]
Hello, @yhimanshu22  
I don't understand what you meant by the "first issue"
- add a comment in the respected issue you want to work on. 

This (Add Footer) issue is already assigned to @akj2018

**Comment by yhimanshu22** [comment]
i am completely new and don't know much how to contribute.

**Comment by murtazajoo** [comment]
@yhimanshu22 let's talk [here](https://github.com/murtazajoo/openSourcer/discussions/15)
